[package]
name = "cosmic_shake_autosplitter_wasm"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]

asr = { git = "https://github.com/CryZe/asr" }
once_cell = "1.17.0"
